import turtle

turtle.penup()
turtle.goto(-200,0)
turtle.pendown()

#김

turtle.forward(50)
turtle.goto(-200,-50)
turtle.penup()
turtle.goto(-130,0)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.goto(-170,-60)
turtle.pendown()
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)

#정

turtle.penup()
turtle.goto(-110,0)
turtle.pendown()
turtle.right(180)
turtle.forward(50)
turtle.penup()
turtle.goto(-85,0)
turtle.pendown()
turtle.goto(-110,-50)
turtle.penup()
turtle.goto(-85,0)
turtle.pendown()
turtle.goto(-60,-50)
turtle.penup()
turtle.goto(-40,0)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.goto(-40,-25)
turtle.pendown()
turtle.right(90)
turtle.forward(20)
turtle.penup()
turtle.goto(-65,-60)
turtle.pendown()
turtle.circle(15)

#혜

turtle.penup()
turtle.goto(-10,-10)
turtle.pendown()
turtle.right(180)
turtle.forward(50)
turtle.penup()
turtle.goto(-20,-25)
turtle.pendown()
turtle.forward(75)
turtle.penup()
turtle.goto(15,-35)
turtle.pendown()
turtle.circle(-20)
turtle.penup()
turtle.goto(60,-15)
turtle.pendown()
turtle.goto(60,-80)
turtle.penup()
turtle.goto(65,-15)
turtle.pendown()
turtle.goto(65,-80)
turtle.penup()
turtle.goto(40,-50)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.goto(40,-60)
turtle.pendown()
turtle.forward(20)
